package main

import (
	"fmt"
	"net"
	"tcp_test/common"
)

func main() {
	dial, err := net.Dial("tcp", "127.0.0.1:8090")
	if err != nil {
		fmt.Println(err)
		return
	}
	util := common.NewSocketUtil(dial)
	for i := 0; i <= 100; i++ {
		util.PkgWrite([]byte("xiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijunxiaobaijun"))
	}
	dial.Close()
}
